# Generated by Django 5.2.3 on 2025-08-28 15:43

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_translations'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
