# Generated by Django 5.2.3 on 2025-09-06 18:53

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='finish_event',
            field=models.DateTimeField(default='2025-10-10 20:20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=5),
        ),
        migrations.AddField(
            model_name='event',
            name='start_event',
            field=models.DateTimeField(default='2025-9-10 20:20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('UP', 'Upcoming'), ('ON', 'Ongoing'), ('CO', 'Completed')], default='Upcoming', max_length=10),
        ),
        migrations.CreateModel(
            name='EventCoordination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_position', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat_position', models.DecimalField(decimal_places=3, max_digits=8)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinations', to='event.event')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventCoordinationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('location_name', models.CharField(max_length=200)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='event.eventcoordination')),
            ],
            options={
                'verbose_name': 'event coordination Translation',
                'db_table': 'event_eventcoordination_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
