# Generated by Django 5.2.3 on 2025-09-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_eventcoordination_lat_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcoordination',
            name='lat_position',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
