# Generated by Django 5.2.3 on 2025-09-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_eventcoordination_lat_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='finish_event',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
