# Generated by Django 5.2.3 on 2025-10-05 16:08

import django.contrib.postgres.indexes
from django.contrib.postgres.search import SearchVector
from django.db import migrations
from django.db.models import Value
from event.models import Event


def compute_search_vector_en(apps, shema_editor):
    events = Event.objects.all()

    for event in events:
        name = event.safe_translation_getter('title', language_code='en')
        description = event.safe_translation_getter('description', language_code='en')
        event.search_vector = SearchVector(Value(name), Value(description), config='english')
        event.search_vector_en = SearchVector(Value(name), Value(description), config='english')

        event.save()



def compute_search_vector_ru(apps, shema_editor):
    events = Event.objects.all()

    for event in events:
        name = event.safe_translation_getter('title', language_code='ru')
        description = event.safe_translation_getter('description', language_code='ru')
        event.search_vector_ru = SearchVector(Value(name), Value(description), config='russian')

        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_finish_event'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='search_vector_en',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='search_vector_ru',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector', 'search_vector_en', 'search_vector_ru'], name='event_event_search__f864b5_gin'),
        ),
        migrations.RunPython(
            compute_search_vector_en, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            compute_search_vector_ru, reverse_code=migrations.RunPython.noop
        )
    ]

