# Generated by Django 5.2.3 on 2025-08-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_translations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductTranslation',
        ),
    ]
