# Generated by Django 5.2.3 on 2025-08-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='slug',
            field=models.SlugField(default='lol', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
