# Generated by Django 5.2.3 on 2025-10-05 08:15

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
from shop.models import Product


def compute_search_vector_en(apps, schema_editor):
    vector = django.contrib.postgres.search.SearchVector("name", "description", config='english')

    products = Product.objects.language("en").all()

    for product in products:
        product.search_vector = vector
        product.search_vector_en = vector


def compute_search_vector_ru(apps, shema_editor):

    vector = django.contrib.postgres.search.SearchVector("name", "description", config='english')

    products = Product.objects.language("en").all()

    for product in products:
        product.search_vector_ru = vector



class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector_en',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector_ru',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector', 'search_vector_ru', 'search_vector_en'], name='shop_produc_search__66cd22_gin'),
        ),
        migrations.RunPython(
            compute_search_vector_en , reverse_code=migrations.RunPython.noop
        ) ,
        migrations.RunPython(
            compute_search_vector_ru , reverse_code=migrations.RunPython.noop
        ) ,
    ]
