# Generated by Django 5.2.3 on 2025-10-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_search_vector_product_search_vector_en_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_search__66cd22_gin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_vector_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_vector_ru',
        ),
    ]
