# Generated by Django 5.2.3 on 2025-10-05 12:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db.models import Value
from django.db import migrations


import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
from shop.models import Product


def compute_search_vector_en(apps, schema_editor):
    products = Product.objects.all()

    for product in products:
        description = product.safe_translation_getter('description' , language_code='en')
        name = product.safe_translation_getter('name', language_code='en')
        product.search_vector = django.contrib.postgres.search.SearchVector(Value(name),
                                                                            Value(description),
                                                                            config='english')
        product.search_vector_en = django.contrib.postgres.search.SearchVector(Value(name),
                                                                            Value(description),
                                                                            config='english')
        product.save()


def compute_search_vector_ru(apps, shema_editor):
    products = Product.objects.all()

    for product in products:
        description = product.safe_translation_getter('description' , language_code='ru')
        name = product.safe_translation_getter('name' , language_code='ru')
        product.search_vector_ru = django.contrib.postgres.search.SearchVector(Value(name) ,
                                                                            Value(description) ,
                                                                            config='russian')

        product.save()



class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_product_shop_produc_search__66cd22_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector_en',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector_ru',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector', 'search_vector_ru', 'search_vector_en'], name='shop_produc_search__66cd22_gin'),
        ),

        migrations.RunPython(
            compute_search_vector_en , reverse_code=migrations.RunPython.noop
        ) ,
        migrations.RunPython(
            compute_search_vector_ru , reverse_code=migrations.RunPython.noop
        ) ,
    ]
